apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pool-deployment
  labels:
    app: worker-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-pool
  template:
    metadata:
      labels:
        app: worker-pool
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9999"
    spec:
      containers:
        - name: worker-pool
          image: worker-pool:0.0.2
          ports:
            - containerPort: 9999