apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-pool-db
  template:
    metadata:
      labels:
        app: worker-pool-db
    spec:
      containers:
        - name: worker-pool-db
          image: postgres:13
          ports:
            - containerPort: 5432
# Все переменные, что нам нужны в Secret
#          env:
#            - name: POSTGRES_USER
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: POSTGRES_USER
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: POSTGRES_PASSWORD
#            - name: POSTGRES_DB
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: POSTGRES_DB
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc